version: '3.8'

services:
  mssql-server:
    build: ./mssql
    container_name: mssql-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Un!q@to2023"

  api-server:
    build: ./api
    container_name: api-container
    ports:
      - "80:80"
    depends_on:
      - mssql-server

